# ----------- CONFIGURABLE START -----------
title:            "YouWidgets"
description:      ""
url:              https://YouWidgets.github.io # 域名
signoff:          "YouWidgets" # Your name
facebook_appid:   
google_analytics: 
share:            true 
# 分页
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         HomePage
    url:          /
    external:     false
  - name:         PrivacyAndPolicy
    url:          /pages/privacy_and_policy_en
    external:     false
  - name:         TermsAndConditions
    url:          /pages/terms_and_conditions_en
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:  /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
